config/routes.rb
Rails.application.routes.draw do

  root 'users#login'
  resources :users do
    member do
      post 'reset-password' => 'users#reset_password'
    end
    collection do
      get 'login' => 'users#login'
      get 'logout' => 'users#logout'
      post 'sessions' => 'users#sessions'
    end
  end

  resources :institutions do
    member do
      get 'list' => 'institutions#list', path: 'list-subjects'
      get 'add' => 'subjects#add', path: 'add-subject'
      get 'remove' => 'subjects#remove', path: 'remove-subject'

      get 'join' => 'institutions#join'
      get 'leave' => 'institutions#leave'

      get 'teachers' => 'institutions#teachers'
      get 'roles' => 'institutions#roles', path: 'user-roles'
    end

  end

  resources :subjects do
    resources :students
      member do
        get 'members' => 'subjects#members'
      end

      resources :announcements
      resources :posts, path: 'discussions' do
      resources :comments, only: [:create, :destroy]
    end
    resources :tasks
    resources :task_types, path: 'task-types'

  end

  resources :past_papers, path: 'past-papers'

end

app/models/institution.rb
class Institution < ActiveRecord::Base
  belongs_to :user

  @@types = ['school', 'varsity', 'online']

  validates_presence_of :name
  validates_presence_of :location
  validates_presence_of :bio
  validates_inclusion_of :institution_type, in: @@types

  before_validation :prepare_data

  def self.types
    return @@types.collect do |type|
      [type.capitalize, type]
    end
  end

  def self.all_for_select(type)

    case type
    when :school
      institutions = self.where(institution_type: 'school')
    else
      institutions = self.all
    end

    return institutions.collect do |institution|
      [institution.name, institution.id]
    end

  end

  protected
    def prepare_data
      self.location = self.location.to_s.strip
      self.name = self.name.to_s.strip
      self.bio = self.bio.to_s.strip
    end
end

app/controllers/institutions_controller.rb
class InstitutionsController < ApplicationController
  before_action :load_institution, except: [:new, :create, :index]
  respond_to :html
  load_and_authorize_resource

  def list
    @subjects = Subject.where(institution_id: @institution.id).order(:name)
  end

  def roles
    @allowed_roles = ['student', 'teacher', 'hr', 'admin', 'tutor']
    role = params[:role] || 'student'

    if @allowed_roles.include?(role)
      if role == 'hr'
        @role_name = 'Human resources'
      else
        @role_name = role.pluralize.capitalize
      end
    else
      role = ''
      @role_name = 'All'
    end

    @users = @users = User.joins(:profile)
    if role != ''
      @users = @users.where(role: role)
    end
    @users = @users.where(profiles: {institution_id: @institution.id}).references(:profiles).order('profiles.fullname ASC, username ASC')
  end

  def index
    @institutions = Institution.all
  end

  def show
  end

  def new
    @institution = Institution.new
  end

  def create
    @institution = Institution.new(institution_params)
    @institution.user_id = current_user.id
    if @institution.save
      flash[:notice] = []
      flash[:notice] << "Institution created successfully"

      # Make this user join the course
      current_user.profile.institution_id = @institution.id
      if !current_user.save
        flash[:alert] = []
        flash[:alert] << "System error: Unable to add you the the institution. Join it manually"
      end
      # redirect_to @institution
      # return
    end

    respond_with(@institution)
  end

  def edit
  end

  def update
    @institution.assign_attributes(institution_params)
    if @institution.save
      flash[:notice] = []
      flash[:notice] << "Institution has been updated"
    end
    respond_with(@institution)
  end

  def destroy
    # TODO: It's important to think about what must happen to everyone who has joined this institution
    if @institution.destroy
      flash[:notice] = []
      flash[:notice] = "Institution was deleted successfully"
    end
    respond_with(@institution)
  end

  def join

    if current_user.profile.institution_id == @institution.id
      flash[:alert] = []
      flash[:alert] << "You are already part of this institution"
    else
      current_user.profile.institution_id = @institution.id
      if current_user.save
        flash[:notice] = []
        flash[:notice] << "You have joined #{@institution.name}"
      end
    end

    redirect_back
  end

  def leave

    if current_user.profile.institution_id == @institution.id
      current_user.profile.institution_id = nil
      if current_user.save
        flash[:notice] = []
        flash[:notice] << "You have left #{@institution.name}"
      end
    else
      flash[:alert] = []
      flash[:alert] << "You are not part of this institution"
    end

    redirect_back
  end

  protected
    def institution_params
      params.require(:institution).permit(:name, :location, :website, :bio, :institution_type)
    end

    def load_institution
      @institution = Institution.find(params[:id])
    end
end

app/helpers/institutions_helper.rb
module InstitutionsHelper
  def format_institution(institution_name, year)
    unless !institution_name
      return "#{institution_name} #{format_year(year)}"
    end
    ""
  end

  def format_year(year)
    if year
      moded_year = year.to_i % 1000
      if moded_year < 10
        year_string = "0#{moded_year}"
      else
        year_string = moded_year.to_s
      end
      return "'#{year_string}" if year
    end
    ""
  end
end

app/views/institutions/_institution.html.haml
= render partial: '/shared/manage', locals: {manageable: institution}
%h4
  = institution.name

%h5
  = institution.location

%h6
  %span.label-field.fa-laptop
  = institution.website

.bg-faded
  .post
    = institution.bio

app/views/institutions/_institution_form.html.haml
= form_for(institution) do |f|
  = render partial: '/shared/form_errors', locals: {objectWithErrors: institution}
  .form-group
    = f.label :name, 'Name*'
    = f.text_field :name, value: institution.name, class: 'form-control', require: true, placeholder: 'Our Awesome High School'
  
  .form-group
    = f.label :location, 'Location*'
    = f.text_field :location, value: institution.location, class: 'form-control', require: true, placeholder: 'Street, Town/City, Province, Country'

  .form-group
    = f.label :institution_type, 'Type*'
    = f.select :institution_type, Institution.types, class: 'form-control', require: true

  .form-group
    = f.label :website
    = f.text_field :website, value: institution.website, class: 'form-control', placeholder: 'www.our-school.co.za'

  .form-group
    = f.label :bio, 'Bio*'
    = f.text_area :bio, value: institution.bio, class: 'form-control', require: true, placeholder: 'Short or long history of school (can be edited later)'

  .rows
    .col-sm-2.col-sm-offset-6
      = link_to 'Cancel', [institution], class: 'btn btn-danger'
    .col-sm-4
      = f.submit nil, class: 'btn btn-primary'

app/views/institutions/_institution_index.html.haml
.row.main-notification-block
  .col-sm-10 
    = link_to institution.name, institution
  .col-sm-2
    - if get_institution_id(current_user) != institution.id
      = link_to 'Join', join_institution_path(institution.id)
    - else
      = link_to 'Leave', leave_institution_path(institution.id)
  %hr

app/views/institutions/_left_bar.html.haml
- content_for :left_bar do
  %ul.nav.nav-stacked
    
    - if can?(:create, Institution)
      %li.nav-item
        = link_to '<span class="fa-plus"></span> Institution'.html_safe, new_institution_path, class: 'nav-link'

  = render partial: '/institutions/left_bar_contents', locals: {institution: institution}

app/views/institutions/_left_bar_contents.html.haml
- if defined?(institution) && institution
  .stacked-nav-title 
    Institution
  .row
    .col-sm-12
      %ul.nav.nav-stacked
        - if can?(:create, Subject)
          %li.nav-item
            = link_to '<span class="fa fa-plus"></span> Subject'.html_safe, new_subject_path, class: 'nav-link'
        %li.nav-item
          .row
            .col-md-12
              = link_to '<span class="fa fa-users"></span> Roles'.html_safe, roles_institution_path(institution)
          .row
            .col-md-12
              %ul.nav.nav-stacked
                %li.nav-item
                  = link_to 'HR', roles_institution_path(institution, role: 'hr'), class: 'nav-link'
                %li.nav-item
                  = link_to 'Students', roles_institution_path(institution, role: 'student'), class: 'nav-link'
                %li.nav-item
                  = link_to 'Teachers', roles_institution_path(institution, role: 'teacher'), class: 'nav-link'
                %li.nav-item
                  = link_to 'Tutors', roles_institution_path(institution, role: 'tutor'), class: 'nav-link'
        %li.nav-item
          = link_to '<span class="fa-align-left"></span> Subjects'.html_safe, list_institution_path(institution), class: 'nav-link'

= render partial: '/shared/subjects_nav'
-# - if defined?(subject) && !subject.nil?
-#   = render partial: '/shared/subject_features', locals: {subject: subject}

app/views/institutions/_right_bar.html.haml
- content_for :right_bar do
  %span

app/views/institutions/edit.html.haml
= render partial: '/institutions/left_bar', locals: {institution: @institution}
= render partial: '/institutions/institution_form', locals: {institution: @institution}
= render partial: '/institutions/right_bar'

app/views/institutions/index.html.haml
= render partial: '/institutions/left_bar', locals: {institution: nil}
= render partial: '/institutions/institution_index', collection: @institutions, as: 'institution'
= render partial: '/institutions/right_bar'

app/views/institutions/list.html.haml
= render partial: '/institutions/left_bar', locals: {subject: nil, institution: nil}
- if @subjects.none?
  .nothing-to-list.text-sm-center
    There is no subject yet, wait for the staff to add them...
- else
  = render partial: '/subjects/subject_index', collection: @subjects, as: 'subject'
= render partial: '/subjects/right_bar', locals: {subject: nil}

app/views/institutions/new.html.haml
= render partial: '/institutions/left_bar', locals: {institution: nil}
= render partial: '/institutions/institution_form', locals: {institution: @institution}
= render partial: '/institutions/right_bar'

app/views/institutions/roles.html.haml
= render partial: '/institutions/left_bar', locals: {institution: @institution}
.row
  .col-sm-12.no-padding
    %h4.title
      = @role_name
  .col-sm-12
    - if @users.any?
      = render partial: '/users/user_index', collection: @users, as: 'user'
    - else
      .nothing-to-list.text-sm-center
        No one has this role...
= render partial: '/users/right_bar'

app/views/institutions/show.html.haml
= render partial: '/institutions/left_bar', locals: {institution: @institution}
= render partial: '/institutions/institution', locals: {institution: @institution}
= render partial: '/institutions/right_bar'