config/routes.rb
Rails.application.routes.draw do

  root 'users#login'
  resources :users do
    member do
      post 'reset-password' => 'users#reset_password'
    end
    collection do
      get 'login' => 'users#login'
      get 'logout' => 'users#logout'
      post 'sessions' => 'users#sessions'
    end
  end

  resources :institutions do
    member do
      get 'list' => 'institutions#list', path: 'list-subjects'
      get 'add' => 'subjects#add', path: 'add-subject'
      get 'remove' => 'subjects#remove', path: 'remove-subject'

      get 'join' => 'institutions#join'
      get 'leave' => 'institutions#leave'

      get 'teachers' => 'institutions#teachers'
      get 'roles' => 'institutions#roles', path: 'user-roles'
    end

  end

  resources :subjects do
    resources :students
      member do
        get 'members' => 'subjects#members'
      end

      resources :announcements
      resources :posts, path: 'discussions' do
      resources :comments, only: [:create, :destroy]
    end
    resources :tasks
    resources :task_types, path: 'task-types'

  end

  resources :past_papers, path: 'past-papers'

end

app/models/past_paper.rb
class PastPaper < ActiveRecord::Base
  @@provinces = [
    'Eastern Cape',
    'Free State', 
    'Gauteng', 
    'Kwa Zulu Natal',
    'Limpopo', 
    'Mpumalanga', 
    'Northen Cape',
    'North West',
    'Western Cape',
  ]

  @@months = [
    'January',
    'February',
    'March',
    'April',
    'May',
    'June',
    'July',
    'August',
    'September',
    'October',
    'November',
    'December'
  ]

  belongs_to :subject
  belongs_to :user

  has_many :attachables
  has_many :attachments, as: :attachable, dependent: :destroy
  accepts_nested_attributes_for :attachments, update_only: true, allow_destroy: true, reject_if: :all_blank

  def self.provinces
    @@provinces.collect do |province|
      [province, province]
    end
  end

  def self.months
    @@months.collect do |month|
      [month, month.parameterize]
    end
  end
end

app/controllers/past_papers_controller.rb
class PastPapersController < ApplicationController
  before_action :load_past_paper, except: [:index, :new, :create]
  respond_to :html
  load_and_authorize_resource

  def index
    @past_papers = PastPaper.all.order(year: :ASC, province: :ASC)
    if params[:subject_type]
      # raise params
      @past_papers = @past_papers.where('lower(subject_type) = ?', params[:subject_type].to_s.downcase)
    end
  end

  def edit
  end

  def update
    @past_paper.assign_attributes(past_paper_params)
    if @past_paper.save
      flash[:notice] = []
      flash[:notice] = "Past paper has been updated successfully"
    end

    respond_with(@past_paper) end 
  
  def new
    @past_paper = PastPaper.new
  end

  def create
    @past_paper = PastPaper.new(past_paper_params)
    @past_paper.user_id = current_user.id
    if @past_paper.save
      flash[:notice] = []
      flash[:notice] << "Past paper has been uploaded successfully"
    end
    respond_with(@past_paper)
  end

  def show
  end

  def destroy
    if @past_paper.destroy
      flash[:notice] = []
      flash[:notice] << "The past paper has been deleted successfully"
    end

    respond_with(@past_paper)
  end

  protected
    def past_paper_params
      params.require(:past_paper).permit(:producer, :paper, :province, :month, :year, :subject_type, :tags, attachments_attributes: [:id, :_destroy, :file])
    end

    def load_past_paper
      @past_paper = PastPaper.find(params[:id])
    end
end

app/helpers/past_papers_helper.rb
module PastPapersHelper
end

app/views/past_papers/_action_menu.html.haml
.stacked-nav-title 
  Past Papers
.row
  .col-sm-12
    %ul.nav.nav-stacked
      %li.nav-item
        = link_to 'List', past_papers_path, class: 'nav-link'

app/views/past_papers/_left_bar.html.haml
- content_for :left_bar do
  = render partial: '/past_papers/action_menu'
  = render partial: '/past_papers/subjects_filter', locals: {featurable: past_paper}
  = render partial: '/past_papers/options', locals: {featurable: past_paper}

app/views/past_papers/_options.html.haml
- if can?(:create, PastPaper)
  .stacked-nav-title
    Past Papers
  .row
    .col-sm-12
      %ul.nav.nav-stacked
        %li.nav-item
          = link_to 'New', new_past_paper_path, class: 'nav-link'

app/views/past_papers/_past_paper.html.haml
= render partial: '/shared/manage', locals: {manageable: past_paper}
.row
  .col-md-2
    = past_paper.producer
  .col-md-2
    = past_paper.paper
  .col-md-3
    = past_paper.province.capitalize
  .col-md-3
    = past_paper.month.capitalize
  .col-md-2
    = past_paper.year
.row
  .col-md-12
    = past_paper.tags

.row.block
  .col-md-12
    = render partial: '/attachments/attachment', collection: past_paper.attachments, as: 'attachment'

app/views/past_papers/_past_paper_form.html.haml
= form_for past_paper do |f|

  .row
    .col-md-2
      .form-group
        = f.text_field :producer, class: 'form-control', placeholder: 'Producer', title: 'eg. IEB'

    .col-md-2
      .form-group
        = f.text_field :paper, class: 'form-control', placeholder: 'Paper', title: 'eg. B1'

    .col-md-3
      .form-group
        = f.select :province, PastPaper.provinces, {}, {class: 'form-control'}

    .col-md-3
      .form-group
        = f.select :month, PastPaper.months, {}, class: 'form-control', placeholder: 'Month', title: 'eg. March'

    .col-md-2
      .form-group
        = f.number_field :year, class: 'form-control', placeholder: 'Year', title: '2012', min: 2005

  .row
    .col-md-4
      .form-group
        = f.label :subject_type, 'Subject Code'
        = f.text_field :subject_type, title: 'This will link this to subjects that have this code', class: 'form-control'
    .col-md-8
      .form-group
        = f.label :tags, 'Tags'
        = f.text_field :tags, title: 'Key words that students can use to find this paper', class: 'form-control', placeholder: 'eg. mathematics, maths'

  .row
    .col-sm-12
      = f.fields_for :attachments do |attachment_builder|
        .form-group.nested-fields
          = attachment_builder.label :file, attachment_builder.object.file_file_name
          = attachment_builder.file_field :file, class: 'form-control'
          = link_to_remove_association 'Remove', attachment_builder
      .links
        = link_to_add_association 'Add', f, :attachments, partial: '/attachments/attachment_field'

  .rows
    .col-sm-2.col-sm-offset-6
      = link_to 'Cancel', past_paper, class: 'btn btn-danger'
    .col-sm-4
      = f.submit nil, class: 'btn btn-primary'
  

app/views/past_papers/_past_paper_index.html.haml
.row.main-notification-block
  .col-sm-12
    %a{href: url_for(past_paper)}
      .row
        .col-md-2
          = past_paper.producer
        .col-md-2
          = past_paper.paper
        .col-md-3
          = past_paper.province.capitalize
        .col-md-3
          = past_paper.month.capitalize
        .col-md-2
          = past_paper.year
      .row
        .col-md-12
          = past_paper.tags

app/views/past_papers/_right_bar.html.haml
- content_for :right_bar do
  %span

app/views/past_papers/_subjects_filter.html.haml
- if current_user && current_user.subjects.any?
  .stacked-nav-title 
    Filter by
  .row
    .col-sm-12
      %ul.nav.nav-stacked
        - current_user.subjects.order(:name).each do |subject|
          %li.nav-item
            = link_to trunc(subject.name, 21), past_papers_path(subject_type: subject.subject_type), class: 'nav-link', title: "#{subject.name}"

app/views/past_papers/edit.html.haml
= render partial: '/past_papers/left_bar', locals: {past_paper: nil}
= render partial: '/past_papers/past_paper_form', locals: {past_paper: @past_paper}
= render partial: '/past_papers/right_bar', locals: {past_paper: nil}

app/views/past_papers/index.html.haml
= render partial: '/past_papers/left_bar', locals: {subject: @subject, past_paper: nil}
- if @past_papers.any?
  = render partial: '/past_papers/past_paper_index', collection: @past_papers, as: 'past_paper'
- else
  .nothing-to-list.text-sm-center
    No past papers have been uploaded yet...
= render partial: '/past_papers/right_bar', locals: {subject: @subject, past_paper: nil}

app/views/past_papers/new.html.haml
= render partial: '/past_papers/left_bar', locals: {past_paper: nil}
= render partial: '/past_papers/past_paper_form', locals: {past_paper: @past_paper}
= render partial: '/past_papers/right_bar', locals: {past_paper: nil}

app/views/past_papers/show.html.haml
= render partial: '/past_papers/left_bar', locals: {subject: @subject, past_paper: nil}
= render partial: '/past_papers/past_paper', locals: {past_paper: @past_paper}
= render partial: '/past_papers/right_bar', locals: {subject: @subject, past_paper: nil}