config/routes.rb
Rails.application.routes.draw do

  root 'users#login'
  resources :users do
    member do
      post 'reset-password' => 'users#reset_password'
    end
    collection do
      get 'login' => 'users#login'
      get 'logout' => 'users#logout'
      post 'sessions' => 'users#sessions'
    end
  end

  resources :institutions do
    member do
      get 'list' => 'institutions#list', path: 'list-subjects'
      get 'add' => 'subjects#add', path: 'add-subject'
      get 'remove' => 'subjects#remove', path: 'remove-subject'

      get 'join' => 'institutions#join'
      get 'leave' => 'institutions#leave'

      get 'teachers' => 'institutions#teachers'
      get 'roles' => 'institutions#roles', path: 'user-roles'
    end

  end

  resources :subjects do
    resources :students
      member do
        get 'members' => 'subjects#members'
      end

      resources :announcements
      resources :posts, path: 'discussions' do
      resources :comments, only: [:create, :destroy]
    end
    resources :tasks
    resources :task_types, path: 'task-types'

  end

  resources :past_papers, path: 'past-papers'

end

app/views/shared/_common_options.html.haml
%li.nav-item
  -# = link_to 'Add', url_for(:new, new_featurable_)

app/views/shared/_form_errors.html.haml
- if objectWithErrors.errors.any?
  .alert.alert-danger{role: 'alert'}
    %ul
      - objectWithErrors.errors.full_messages.each do |message|
        %li
          = message
    

app/views/shared/_manage.html.haml
.row.manage
  .col-sm-2.col-sm-offset-10.text-sm-right
    - if can?(:edit, get_manageable_object(manageable))
      = link_to '', edit_url(manageable), class: 'fa fa-edit'
    - if can?(:destroy, get_manageable_object(manageable))
      = link_to '', delete_url(manageable), method: :delete, data: {confirm: 'Are you sure you want to delete this?'}, class: 'fa fa-close'

app/views/shared/_post_details.html.haml
.row.user-post-text.post-details
  .col-md-4.col-md-offset-3
    - if updated?(post)
      = render partial: '/shared/time', locals: {time: post.updated_at, isUpdate: true}
  .col-md-4.col-md-offset-1
    = render partial: '/shared/user_post', locals: {user: post.user, post: post}

app/views/shared/_post_index_details.html.haml
.row
  .col-md-4.col-md-offset-1{title: post.subject.name}
    = link_to trunc(post.subject.name, 15), post.subject
  .col-md-7.text-sm-right
    By
    = link_to "@#{get_username(post.user)}", post.user
    = render partial: '/shared/time', locals: {time: post.created_at}

app/views/shared/_search.html.haml
= form_tag "#{controller}/search", class: 'form-inline pull-md-right' do

  - if current_user.profile.institution
    = link_to "School", current_user.profile.institution, class: 'btn btn-primary'

  -# = text_field_tag :term, params[:text], class: 'form-control', placeholder: 'Search'
  -# = submit_tag 'Search', class: 'btn btn-success-outline'

  - if current_user
    = link_to 'Logout', logout_users_path, class: 'btn btn-warning'

app/views/shared/_subject_features.html.haml
- if subject
  .stacked-nav-title{title: subject.name}
    = trunc(subject.name)
  .row
    .col-sm-12
      %ul.nav.nav-stacked
        %li.nav-item
          = link_to 'Announcements', subject_announcements_path(subject), class: 'nav-link'
        %li.nav-item
          = link_to 'Discussions', subject_posts_path(subject), class: 'nav-link'
        %li.nav-item
          = link_to 'Tasks', subject_tasks_path(subject), class: 'nav-link'
        -# %li.nav-item
        -#   = link_to 'Past Papers', subject_past_papers_path(subject), class: 'nav-link'

app/views/shared/_subjects_nav.html.haml
- if current_user && current_user.subjects.any?
  .stacked-nav-title 
    Your subjects
  .row
    .col-sm-12
      = render partial: '/users/user_subject_list', locals: {user: current_user}

app/views/shared/_time.html.haml
- if defined?(isUpdate) && isUpdate
  - postText = "Edited"
- else
  -postText = "posted"
- if postText == "Edited"
  %span{title: format_time(time), data: {create: time.iso8601}}
    = "#{postText} #{format_time(time)}"
- else
  %span.time{title: format_time(time), data: {create: time.iso8601}}
    = "#{postText} #{format_time(time)}"

app/views/shared/_user_post.html.haml
.row
  .col-sm-12
    -# The actual user info
    .row{title: get_fullname(user)}
      .col-sm-2.no-padding
        %img.img-fluid{src: user.profile.image.url(:small), alt: 'DP'}
      .col-sm-10
        .row
          .col-sm-12.small-padding
            = link_to "@#{get_username(user)}", user
          .col-sm-12.small-padding

            = render partial: '/shared/time', locals: {time: post.created_at}

app/views/shared/access_denied.html.haml
- cache 'access-denied' do
  .access-denied
    Access Denied: You don't have permission for such action