config/routes.rb
Rails.application.routes.draw do

  root 'users#login'
  resources :users do
    member do
      post 'reset-password' => 'users#reset_password'
    end
    collection do
      get 'login' => 'users#login'
      get 'logout' => 'users#logout'
      post 'sessions' => 'users#sessions'
    end
  end

  resources :institutions do
    member do
      get 'list' => 'institutions#list', path: 'list-subjects'
      get 'add' => 'subjects#add', path: 'add-subject'
      get 'remove' => 'subjects#remove', path: 'remove-subject'

      get 'join' => 'institutions#join'
      get 'leave' => 'institutions#leave'

      get 'teachers' => 'institutions#teachers'
      get 'roles' => 'institutions#roles', path: 'user-roles'
    end

  end

  resources :subjects do
    resources :students
      member do
        get 'members' => 'subjects#members'
      end

      resources :announcements
      resources :posts, path: 'discussions' do
      resources :comments, only: [:create, :destroy]
    end
    resources :tasks
    resources :task_types, path: 'task-types'

  end

  resources :past_papers, path: 'past-papers'

end

app/models/subject.rb
class Subject < ActiveRecord::Base
  YEAR_OF_CREATION = 2016
  belongs_to :user
  belongs_to :institution
  has_many :students
  has_many :users, through: :students, dependent: :destroy
  has_many :announcements, dependent: :destroy
  has_many :posts, dependent: :destroy
  has_many :tasks, dependent: :destroy
  has_many :task_types, dependent: :destroy

  validates_presence_of :name
  validates_presence_of :year
  validates_numericality_of :year, greater_than_or_equal_to: YEAR_OF_CREATION
  validates_presence_of :subject_type

  before_validation :prepare_data

  protected
    def prepare_data
      self.name = self.name.to_s.strip
      self.subject_type = self.subject_type.to_s.strip

      self.year = self.year.to_i.abs
      # self.year = YEAR_OF_CREATION if self.year < YEAR_OF_CREATION
    end
end

app/controllers/subjects_controller.rb
class SubjectsController < ApplicationController
  before_action :load_subject, except: [:new, :create, :index, :list]
  respond_to :html
  load_and_authorize_resource

  def index
    if current_user.profile.institution
      @subjects = current_user.subjects.order(:name)
    else
      flash[:alert] = []
      flash[:alert] << "Please join your school on the list before going to the subjects"
      redirect_to institutions_path
    end
  end

  def new 
    @subject = Subject.new 
  end

  def create
    @subject = Subject.new(subject_params)
    @subject.user_id = current_user.id
    @subject.institution_id = current_user.profile.institution_id

    if @subject.save
      flash[:notice] = []
      flash[:notice] << "#{@subject.name} was created successfully"
    end
    
    if @subject.persisted?
      redirect_to list_institution_path(@subject.institution)
    else
      respond_with(@subject)
    end
  end

  def edit
  end

  def update
    @subject.assign_attributes(subject_params)
    if @subject.save
      flash[:notice] = []
      flash[:notice] << "#{@subject.name} was been updated successfully"
    end

    respond_with(@subject)
  end

  def members
    @members = Student.for_subject(@subject.id)
  end

  def show
    @announcements = @subject.announcements.limit(5).order(updated_at: :DESC)
  end

  def destroy
    subject_name = @subject.name
    delete_operation = false
    if @subject.destroy
      delete_operation = true
      flash[:notice] = []
      flash[:notice] = "#{subject_name} was created successfully"
    end
    if !delete_operation
      respond_with(@subject)
    else
      redirect_to @subject.institution
    end
  end

  def add
    @student = Student.where(subject_id: @subject.id, user_id: current_user.id).first
    if @student.nil?
      @student = Student.new(subject_id: @subject.id, user_id: current_user.id, accepted:  false)
      flash[:notice] = []
      if @student.save
        flash[:notice] << "The subject has been added successfully"
      else
        flash[:alert] << "System error: Could not add the subject"
      end
    else
      flash[:alert] = []
      flash[:alert] << "You have already added this subject"
    end

    redirect_back
  end

  def remove
    @student = Student.where(subject_id: @subject.id, user_id: current_user.id).first

    if !@student.nil?
      if @student.destroy
        flash[:notice] = []
        flash[:notice] << "The subject has been removed successfuly"
      else
        flash[:alert] = []
        flash[:alert] << "Server error: Could not remove the subject"
      end
    else
      flash[:alert] = []
      flash[:alert] << "You can not remove a subect you have not added"
    end

    redirect_back
  end

  protected
    def subject_params
      params.require(:subject).permit(:name, :year, :subject_type, :other_subject_type)
    end

    def load_subject
      @subject = Subject.find(params[:id].to_i)
    end

end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/views/subjects/_left_bar.html.haml
- content_for :left_bar do
  = render partial: '/subjects/left_bar_contents', locals: {subject: subject}
  - if can?(:create, TaskType)
    = render partial: '/task_types/task_types_nav', locals: {subject: subject}

app/views/subjects/_left_bar_contents.html.haml
- if subject
  .stacked-nav-title 
    Subject
  .row
    .col-sm-12
      %ul.nav.nav-stacked
        %li.nav-item
          = link_to 'Members', members_subject_path(subject), class: 'nav-link'

= render partial: '/shared/subjects_nav'
- if defined?(subject) && !subject.nil?
  = render partial: '/shared/subject_features', locals: {subject: subject}

app/views/subjects/_right_bar.html.haml
- content_for :right_bar do
  = render partial: '/subjects/right_bar_contents', locals: {subject: subject}

app/views/subjects/_right_bar_contents.html.haml
= render partial: '/subjects/right_bar_subject_title', locals: {subject: subject}

app/views/subjects/_right_bar_subject_title.html.haml
- if subject
  %h3{title: subject.name}
    = link_to trunc(subject.name), subject

app/views/subjects/_subject.html.haml
.announcements
  = render partial: '/announcements/announcement', locals: {subject: subject, announcement: announcement, manageable: false}

app/views/subjects/_subject_form.html.haml
= form_for subject do |f|
  = render partial: '/shared/form_errors', locals: {objectWithErrors: subject}
  .form-group
    = f.label :name
    = f.text_field :name, class: 'form-control', placeholder: 'Mathematics'

  .form-group
    = f.label :year
    = f.number_field :year, class: 'form-control', placeholder: '2016'

  .form-group{title: 'We use this code to associate this subject with other uploaded past papers'}
    = f.label :subject_type, 'Subject Code/Name (Government code for subject)'
    = f.text_field :subject_type, class: 'form-control', placeholder: 'Mathematics'

  .rows
    .col-sm-2.col-sm-offset-6
      = link_to 'Cancel', list_institution_path(current_user.profile.institution), class: 'btn btn-danger'
    .col-sm-4
      = f.submit nil, class: 'btn btn-primary'

  

app/views/subjects/_subject_index.html.haml
.row.main-notification-block
  .col-sm-10 
    = link_to subject.name, subject
  .col-sm-2
    - if !current_user.subjects.pluck(:id).include?(subject.id)
      = link_to 'Add', add_institution_path(subject.id)
    - else
      = link_to 'Remove', remove_institution_path(subject.id)
  %hr

app/views/subjects/_subject_preview.html.haml
.row.main-notification-block
  .col-sm-10 
    = link_to subject.name, subject
  .col-sm-2
    - if can?(:add, subject) && !current_user.subjects.where(id: subject.id).first
      = link_to 'Add', add_institution_path(subject.id)
    - else
      - if can?(:remove, subject)
        = link_to 'Remove', remove_institution_path(subject.id), class: 'small-anchor-text', data: {confirm: 'Are you sure you want to remove this subject?'}
  .col-sm-12
    .row
      .col-sm-4.index-block
        = link_to "Announcements (#{subject.announcements.count})", subject_announcements_path(subject)
      .col-sm-4.index-block
        = link_to "Discussions (#{subject.posts.count})", subject_posts_path(subject)
      .col-sm-4.index-block
        = link_to "Tasks (#{subject.tasks.count})", subject_tasks_path(subject)
  %hr

app/views/subjects/edit.html.haml
= render partial: '/subjects/left_bar', locals: {subject: @subject}
= render partial: '/subjects/subject_form', locals: {subject: @subject}
= render partial: '/subjects/right_bar', locals: {subject: @subject}

app/views/subjects/index.html.haml
= render partial: '/subjects/left_bar', locals: {subject: nil}
- if @subjects.none?
  .nothing-to-list.text-sm-center
    %h4
      You have no subject. Choose them from this
      = link_to 'list', list_institution_path(current_user.profile.institution)
      \.
- else
  = render partial: '/subjects/subject_preview', collection: @subjects, as: 'subject'
= render partial: '/subjects/right_bar', locals: {subject: nil}

app/views/subjects/members.html.haml
= render partial: '/subjects/left_bar', locals: {subject: @subject}
= render partial: '/subjects/right_bar', locals: {subject: @subject}

-# = render partial: '/subjects/subject', locals: {subject: @subject}
%h2
  Members
.students
  = render partial: '/users/user_subject_member', collection: @members, as: 'member', locals: {subject: @subject}

app/views/subjects/new.html.haml
= render partial: '/subjects/left_bar', locals: {subject: nil}
= render partial: '/subjects/subject_form', locals: {subject: @subject}
= render partial: '/subjects/right_bar', locals: {subject: nil}

app/views/subjects/show.html.haml
= render partial: '/subjects/left_bar', locals: {subject: @subject}
= render partial: '/subjects/right_bar', locals: {subject: @subject}

= render partial: '/shared/manage', locals: {manageable: @subject}

.row.block
  .col-sm-12
    - if @announcements.any?
      %h4.index-subject-title.pull-up-1
        Last 5 announcements
    - else
      %h4.index-subject-title
        Last 5 announcements

  .col-sm-12
    - if @announcements.any?
      = render partial: '/subjects/subject', collection: @announcements, as: 'announcement', locals: {subject: @subject, manageable: false}
    - else
      .nothing-to-list.text-sm-center
        No announcements to show last 5...